repos:
  - "http://negativo17.org/repos/fedora-spotify.repo"
  - "http://negativo17.org/repos/fedora-steam.repo"

copr_repos:
  - mosquito/atom

packages:
  - spotify-client
  - google-chrome-stable
  - terminator
  - git
  - ansible
  - docker
  - bash-completion
  - wine
  - steam
  - boxes
  - drpm
  - gnome-tweak-tool
  - tmux
  - vim
  - powertop
  - bluejeans
  - mutt
  - weechat
  - httpd

