---
#
# Need to find a generic way of doing this
#

  - include_tasks: dnf.yml
    with_items: "{{ repos }}"
    when: ansible_pkg_mgr == 'dnf'

  - include_tasks: pacman.yml
    with_items: "{{ repos }}"
    when: ansible_pkg_mgr == 'pacman'

  - include_tasks: apt.yml
    with_items: "{{ repos }}"
    when: ansible_pkg_mgr == 'apt'
