---
- hosts: install
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - role: repos
      when: repos is defined
    - role: packages
      when: packages is defined
    - role: flatpak
      when: flatpak_remotes is defined or flatpaks is defined
    - role: snap
      when: snaps is defined or snaps_classic is defined
    - role: security
      when: selinux is defined and selinux | bool
    - role: shell
      when: shell is defined and username is defined
    - role: user
      when: username is defined
    - role: external_packages
      when: external_packages is defined
    - role: configs
      when: configs is defined
    - role: fonts
      when: fonts is defined
    - role: dconf
      when: dconf_settings is defined
    - role: update
      when: system_upgrade | default('false') | bool
  tasks:
###
# Add custom tasks here. These will be run after the roles above.
###
  - name: "Configure ignore-case auto completion"
    lineinfile:
      path: /etc/inputrc
      state: present
      regexp: "^set completion-ignore-case"
      line: "set completion-ignore-case on"

  - name: "Enable passwordless sudo for {{ username }}"
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "^{{ username }}"
      line: "{{ username }}         ALL=(ALL) NOPASSWD:ALL"

