---
- hosts: install
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - role: repos
      when: repos is defined
    - role: packages
      when: packages is defined
    - role: flatpak
      when: flatpak_remotes is defined or flatpaks is defined
    - role: security
      when: selinux is defined and selinux | bool
    - role: user
      when: username is defined
    - role: update
      when: system_upgrade | default('false') | bool
  tasks:

###
# Add custom tasks here. These will be run after the roles above.
###

  - name: "Enable passwordless sudo for wheel group"
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "^%wheel"
      line: "%wheel  ALL=(ALL)       NOPASSWD: ALL"

  - name: "Disable ansible retry files"
    lineinfile:
      state: present
      path: /etc/ansible/ansible.cfg
      regexp: 'retry_files_enabled'
      line: 'retry_files_enabled = False'
