version: 3

tasks:

  install:
    dir: .
    cmds:
      - "./setup.sh"

  test:
    vars:
      entrypoint: ./setup.sh
    dir: .
    cmds:
      - "podman run -it --rm -w /test -v .:/test:Z --entrypoint={{.entrypoint}} fedora:42"

  tpackages:
    dir: .
    vars:
      entrypoint: ./scripts/packages.sh
    cmds:
      - "podman run -it --rm -w /test -v .:/test:Z --entrypoint={{.entrypoint}} fedora:42"

  tshell:
    dir: .
    vars:
      entrypoint: ./scripts/shell.sh
    cmds:
      - "podman run -it --rm -w /test -v .:/test:Z --entrypoint={{.entrypoint}} fedora:42"

  tomz:
    dir: .
    vars:
      entrypoint: ./scripts/omzsh.sh
    cmds:
      - "podman run -it --rm -w /test -v .:/test:Z --entrypoint={{.entrypoint}} fedora:42"
