---

  - name: "Install ansible module dependencies"
    ansible.builtin.package:
      name: "python-xml,python3-psutil,python3-dnf,firewalld,python3-firewall,python3-libselinux"
      state: present

  - name: "Installing packages"
    ansible.builtin.package:
      name: "{{ packages + [shell] }}"
      state: present



