---

  - name: "Install ansible module dependencies"
    ansible.builtin.dnf:
      name: "python3-psutil,python3-dnf,firewalld,python3-firewall,python3-libselinux"
      state: present

  - name: "Installing packages"
    ansible.builtin.dnf:
      name: "{{ packages + [shell] }}"
      state: present
      skip_broken: true # skip any issues found between rpmfusion + core
