---

  - name: "Install ansible module dependencies"
    package:
      name: "{{ item }}"
      state: present
    loop:
      - "python3-psutil"
      - "python3-dnf"
      - "firewalld"
      - "python3-firewall"
      - "python3-libselinux"

  - name: "Installing packages"
    package:
      name: "{{ packages }}"
      state: present



