---


  - set_fact:
      packages: "{{ dnf_packages }}"
    when: ansible_pkg_mgr == 'dnf'

  - set_fact:
      packages: "{{ pacman_packages }}"
    when: ansible_pkg_mgr == 'pacman'

  - name: "Installing packages"
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ packages }}"



