---

  - name: "Install ansible module dependencies (Red Hat family)"
    package:
      name: "{{ item }}"
      state: present
    loop:
      - "python2-psutil"
      - "python2-dnf"
      - "firewalld"
      - "python3-firewall"
      - "libselinux-python"
    when: ansible_os_family == 'RedHat'

  - name: "Install ansible module dependencies (Debian family)"
    package:
      name: "{{ item }}"
      state: present
    loop:
      - "python-apt"
      - "python3-apt"
    when: ansible_os_family == 'Debian'

  - name: "Installing packages"
    package:
      name: "{{ packages }}"
      state: present



