---

  - name: "Install ansible module dependencies"
    package:
      name: "python3-psutil,python3-dnf,firewalld,python3-firewall,python3-libselinux"
      state: present

  - name: "Installing packages"
    package:
      name: "{{ packages + [shell] }}"
      state: present



