---

  - name: "Enable firewalld"
    service:
      state: started
      enabled: yes
      name: firewalld


  - name: "Enable SElinux"
    selinux:
      state: enforcing
      policy: targeted
    when: ansible_selinux_python_present

