# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$PATH
export EDITOR=/usr/bin/nvim
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"


plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  z
)


source $ZSH/oh-my-zsh.sh
### USER CONFIGURATION ###

# Go Development
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin/

#
# Completions
#

if [ -f $HOME/.local/bin/kubebuilder ]; then
. <(kubebuilder completion zsh)
fi

if [ -f /usr/bin/kubectl ]; then
source <(kubectl completion zsh)
fi

autoload -U +X bashcompinit && bashcompinit

#
# Aliases
#
alias vim="nvim"
alias poweroff="sudo systemctl poweroff"
alias reboot="sudo systemctl reboot"
alias k="kubectl"
