# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$PATH
export EDITOR=/usr/bin/nvim
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="avit"

plugins=(
  git
  zsh-autosuggestions
  tmux
)
source $ZSH/oh-my-zsh.sh
ZSH_TMUX_AUTOSTART=true

# Fix background color on text
eval "$(dircolors -p | \
    sed 's/ 4[0-9];/ 01;/; s/;4[0-9];/;01;/g; s/;4[0-9] /;01 /' | \
    dircolors /dev/stdin)"
autoload -U compinit; compinit


##### USER CONFIGURATION #####
# Go Development
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin/
[[ -s "/home/jkwiatko/.gvm/scripts/gvm" ]] && source "/home/jkwiatko/.gvm/scripts/gvm"

# kubectl autocomplete
source <(kubectl completion zsh)
alias k=kubectl
alias vim='nvim'

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi
