# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

#Uncomment the following line if you don't like systemctl's auto-paging feature:

# export SYSTEMD_PAGER=
GREEN="\[$(tput setaf 46)\]"
BLUE="\[$(tput setaf 39)\]"
RESET="\[$(tput sgr0)\]"
# User specific aliases and functions
export PS1="${BLUE}\u@\h \w\n$ ${RESET}"
alias ..="cd .."
alias vi="vim"
source <(kubectl completion bash)

