# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export PS1="\[\033[38;5;114m\]\u\[$(tput sgr0)\]@\h:\W\n> \[$(tput sgr0)\]"
# User specific aliases and functions
alias ..="cd .."
alias vi="vim"
alias dovpn="sudo openconnect --protocol=gp https://vpn-nyc3.digitalocean.com/ssl-vpn -u jkwiatkoski "
source <(kubectl completion bash)
