"plugins
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()

"visual
syntax enable
syntax on
set background=dark

"search
set ignorecase "case insensitive
set smartcase  "use case if any caps used
set incsearch  "show match as search proceeds

"indent
set autoindent

"ignore
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.o


"temp files
set nobackup
set nowritebackup
set noswapfile

"tab sizes
set tabstop=4

"Disable arrows
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
