---
dnf_packages:
  - python2-dnf
  - firewalld
  - python-firewall
  - libselinux-python
  - spotify-client
  - git
  - steam
  - boxes
  - drpm
  - gnome-tweak-tool
  - tmux
  - vim
  - powertop

pacman_packages:
  - firewalld
  - yaourt
  - git
  - steam-manjaro
  - tmux
  - vim
