---

  - name: "Check username is defined"
    fail:
      msg: "username is not set"
    when: username is undefined

  - name: "Add bash configurations"
    copy:
      src: rc
      dest: "/home/{{ username }}/.bashrc"

  - name: "Add bash profile"
    copy:
      src: profile
      dest: "/home/{{ username }}/.bash_profile"

  - name: "Add root bash configurations"
    copy:
      src: rc
      dest: "/root/.bashrc"

  - name: "Add root bash profile"
    copy:
      src: profile
      dest: "/root/.bash_profile"

  - name: "Setup firewalld for VM's"
    firewalld:
      state: enabled
      interface: virbr0
      permanent: yes
      zone: trusted
      immediate: yes

  - name: "Add Atom repo"
    command: "dnf -y copr enable {{ item }}"
    with_items:
      - "{{ copr_repos }}"

  - name: "Add Google Chrome repo"
    copy:
      src: google-chrome.repo
      dest: /etc/yum.repos.d/google-chrome.repo

  - name: "Add Steam repo"
    command: "dnf config-manager --add-repo={{ item }}"
    with_items:
      - "{{ repos }}"

  - name: "Add RPMFusion repos"
    shell: "dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

  - name: "Update packages"
    dnf:
      name: "*"
      state: latest

  - name: "Install packages"
    dnf:
      name: "{{ item }}"
      state: latest
    with_items:
      - "{{ packages }}"
