---

# Configure ZSH
  - name: "Install OhMyZsh"
    become_user: "{{ username }}"
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    register: result
    failed_when: result.rc != 0 and not "'You already have Oh My Zsh installed.' in result.stdout"
    when: shell == 'zsh' and ohmyzsh

  - name: "Template and distribute specified configuration files"
    copy:
      src: "{{ item.file }}"
      dest: "{{ item.dest }}"
      owner: "{{ username }}"
      group: "{{ username }}"
    with_items:
      - "{{ configs }}"
    when: configs is defined
