---

  - name: "Template and distribute specified configuration files"
    template:
      src: "{{ item.template }}"
      dest: "{{ item.dest }}"
    with_items:
      - "{{ configs }}"
    when: configs is defined
