---

  - name: "Install Vivaldi"
    command: yaourt --noconfirm -S vivaldi
    when: browser == 'vivaldi' and ansible_pkg_mgr == 'pacman'
    become: no

  - name: "Install Firefox"
    package:
      name: firefox
      state: latest
    become: yes
    when: firefox in browser

  - name: "Install Chromium"
    package:
      name: chromium
      state: latest
    become: yes
    when: chromium in browser
