---

  - name: "Download external packages"
    uri:
      url: "{{ item }}"
      dest: "/tmp/"
    with_items:
      - "{{ external_packages }}"

  - name: "Install external packages"
    become: yes
    package:
      name: "/tmp/{{ item | urlsplit('path') | basename }}"
      state: present
    with_items: 
      - "{{ external_packages }}"
  
