
# These variables below will apply to all hosts listed under the 'install' group.

# 
# Don't SSH configuring localhost
# Comment this line below if configuring via ssh
#ansible_connection: local

#
# User 
# User name of a single user to create.
#
username: userA

# 
# Shell
# Which Shell to use. Ensure the shell is installed in packages list.
#
shell: bash

# 
# External Packages
#
# These are a list of URL's to packages that are external to the
# distribution's repositories and will be downloaded and installed.
#
# Ex: external_packages:
#       - "https://downloads.vivaldi.com/stable/vivaldi-stable-1.14.1077.60-1.x86_64.rpm"
# external_packages: ""

#
# Packages
# A list of packages to install from configured repositories.
# Set 'system_upgrade' to yes|true to upgrade all packages.
#
packages:
 - "python2-dnf"
 - "firewalld"
 - "python3-firewall"
 - "libselinux-python"
 - "spotify-client"
 - "steam"
 - "git"
 - "virt-manager"
 - "qemu-kvm"
 - "drpm"
 - "tmux"
 - "vim"
 - "powertop"
 - "weechat"
system_upgrade: no


# 
# Repositories
# Additional repositories to enable.
repos:
 - "http://negativo17.org/repos/fedora-spotify.repo"
 - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm"
 - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm" 


# 
# Security
# Whether to enable selinux.(If supported by your distribution.)
selinux: yes

#
# Configs
# Place your desired configurations in the 'roles/configs/files' directory
# then populate the 'configs' variable below.
# examples: .vimrc, .bashrc, .bash_profile,
configs:
  - file: bashrc
    dest: /home/{{ username }}/.bashrc
  - file: bash_profile
    dest: /home/{{ username }}/.bash_profile
 
# 
# Fonts
# Install fonts not a part of default repositories.
# If fonts are distributed via the default repositories, add the font package name to the `packages` variable above.
fonts:
  - "https://assets.ubuntu.com/v1/fad7939b-ubuntu-font-family-0.83.zip"


# Manjaro packages(WARN: Will no longer develop for Arch based distributions)
# An example of how package names may differ by distribution. Simply uncomment the list for the distro you're installing
#packages=["fish", "firewalld", "python-firewall", "libselinux-python", "git", "virt-manager", "tmux", "vim", "powertop", "yaourt"]
