---
# tasks file for fonts

 - name: "Ensure fonts varible defined"
   fail:
     msg: "'fonts' is not defined"
   when: fonts is not defined or fonts == ''

 - name: "Create ~/.fonts directory"
   file:
     state: directory
     path: "/home/{{ username }}/.fonts"
     
 - name: "Download and extract fonts"
   unarchive:
     dest: "/home/{{ username }}/.fonts"
     src: "{{ item }}"
     remote_src: yes
   when: "'http' in item"
   with_items: "{{ fonts }}"

 - name: "Update font cache"
   command: "fc-cache"

